Sprint9 master/dev PR
zhebera/PlaylistMaker pull request #3
Opened 2023-06-02 06:32 UTC by zhebera

Создана темная тема, добавлены обработчики кнопок в SettingsActivity, добавлены изменения в коде в SearchActivity со строкой поиска.

2023-06-02 15:16 UTC, NoDopezzz requested changes

2023-06-02 15:16 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +        val textWatcher = object: TextWatcher{
⏫ Зачастую, чтобы избавиться от необходимости переопределения методов, которые мы не хотим использовать, можно создать интерфейс с дефолтной пустой реализацией этих методов.

Например, можно создать такой интерфейс:

```
private interface SimpleTextWatcher : TextWatcher {

        override fun afterTextChanged(s: Editable?) = Unit

        override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) = Unit

        override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) = Unit
    }

```

И в месте определения слушателя достаточно лишь переопределить только нужные методы.

💡Также можно воспользоваться одним из следующих методов:

*`doOnTextChanged`,* `doBeforeTextChanged` или `doAfterTextChanged` с передачей лямбды, которые под капотом реализуют одну из функций интерфейса `TextWatcher`. Или же мы можем воспользоваться универсальным методом `addTextChangedListener` и передать лямбду для каждой реализации интерфейса.

2023-06-02 15:16 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +        var SAVED_SEARCH_EDIT_TXT: String? = null
⚠️`companion object` является синглтоном, к которому можно обращаться через класс. Если сохранять значение  внутри него, то оно будет хранится в памяти постоянно для разных инстансов `SearchActivity`. 
Сейчас если ввести значение в поле ввода, а затем перезайти на экран поиска, то значение сохранится.

Стоит перенести переменную в тело класса, вместо сохранение его в `companion object`.

2023-06-02 15:16 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +        var SAVED_SEARCH_EDIT_TXT: String? = null
В Kotlin переменные именуются в стиле `camelCase`. В стиле `snake_case` в uppecase'е используются только для констант

2023-06-02 15:16 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +    private fun clearButtonVisibility(s: CharSequence?): Int {
⏫ Для изменения видимости элемента на экране можно использовать `extension` `View.isVisible`:

- `View.isVisible = true` соответствует `View.visibility = View.VISIBLE`
- `View.isVisible = false` соответствует `View.visibility = View.GONE`

2023-06-02 15:16 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
> +            intent.data = Uri.parse("mailto:")
⏫ Чтобы обращаться к одной переменной было проще, можно изменять ее внутри одной scope function - [apply](https://kotlinlang.org/docs/scope-functions.html#apply).

2023-06-02 15:16 UTC, kirillNay commented on app/src/main/res/drawable-night/arrow_back.xml
> +      android:fillColor="#ffffff"/>
⏫ Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в `drawable` и `drawable-night`, мы можем создать одну иконку в `drawable`, а файл ресурса с цветом будет задан в `values` и `values-night`.

2023-06-02 15:16 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +                android:textStyle="bold"
⚠️ Обрати внимание, что `textStyle = bold` соответствует весу **700**, но по макетам вес равен **500**.


⏫Желательно стиль заголовка вынести в `styles.xml`, чтобы переиспользовать стиль и на других экранах - Настройки и Плейлисты (добавится в дальнейших спринтах)

2023-06-02 15:16 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +        <ImageView
⚠️ Иконка крестика не находится посередине поля ввода. Стоит немного поправить отступ. Это можно сделать с помощью `layout_gravity` следующим образом: `end|center_vertical`

2023-06-02 15:16 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +                android:maxLines="1"
⚠️Чтобы аттрибут `maxLines` отрабатывало корректно необходимо также установить `android:inputType="text"`

2023-06-02 15:16 UTC, NoDopezzz commented on app/src/main/res/values/colors.xml
> +    <color name="edit_text_insert_txt">#AEAFB4</color>
⚠️ Для `EdtiText` как раз используется такой же цвет, как и в `text_color`

2023-06-02 15:16 UTC, NoDopezzz commented on app/src/main/res/values/styles.xml
> +    <style name="SettingsActivityTextView">
⚠️ Обрати внимание, стиль разных пунктов меню отличается друг от друга
<img width="300" alt="image" src="https://github.com/zhebera/PlaylistMaker/assets/56832972/3a46b9ea-4ae9-469e-be0e-c65ab2cf8cde">

2023-06-03 11:51 UTC, zhebera commented
**По критическим замечаниям**:
1. переменную, в которой сохранялся текст поиска, вынес из **companion object** и внес в тело класса
2. добавил во все TextView параметр _fontWeight_, согласно макетам разметки (**bold=500**, обычные=400)
3. перенес иконку удаления текста в EditText _центральнее относительно вертикали_, как мне и подсказали
4. добавил атрибут _android:inputType="text"_ и изменил цвет ввода текста EditText поиска
5. Привел _к единому стилю_ TextView и текст Switch в файле разметки **настроек**

2023-06-03 15:10 UTC, NoDopezzz approved these changes

2023-06-05 06:21 UTC, merged